opt_out_usage

default_platform(:android)

platform :android do

  desc "Firebase App Distribution"

  lane :firebase_distribution do

    sh "flutter clean"
    sh "flutter pub get"

    sh "flutter build apk --release --flavor production --target lib/main_production.dart"

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      service_credentials_file: "service-account.json",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      release_notes: "New build"
    )

  end

end