# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
     firebase_app_distribution(
  app: "1:290000673195:android:464cafcc2d3ff0e7499aee",
  android_artifact_type: "APK",
  android_artifact_path: "C:/apps_practice/doctor/build/app/outputs/flutter-apk/app-production-release.apk",
  groups: "qa-team, trusted-testers",
  release_notes: "New version of the app is available for testing."
)
  end

end
